CREATE TABLE Kayttajat(KayttajaID INT AUTO_INCREMENT PRIMARY KEY,
Nimi VARCHAR(50) NOT NULL,
Gmail VARCHAR(50) NOT NULL,
SalasanaHash VARCHAR(255)NOT NULL,
PuhelinNro VARCHAR(50)
);

CREATE TABLE Huoneet(HuoneID INT AUTO_INCREMENT PRIMARY KEY,
HuoneNimi VARCHAR(50),
Kerros VARCHAR(50) NOT NULL,
Paikat VARCHAR(50)NOT NULL);

CREATE TABLE Varaukset(VarausID INT AUTO_INCREMENT PRIMARY KEY,
KayttajaID INTEGER NOT NULL,
HuoneID INTEGER NOT NULL,
VarattuAika INTEGER NOT NULL,
VarausStatus VARCHAR(50) NOT NULL,
FOREIGN KEY (KayttajaID) REFERENCES Kayttajat(KayttajaID),
FOREIGN KEY(HuoneID) REFERENCES Huoneet(HuoneID));